### ISSUE TITLE
Master Fails to Run on Linux

### ISSUE THREAD

**Issue by uppaljs** [fermino/WhatsBot#22]
Hi,

Master is causing the following error

php WhatsBot.php 

PHP Parse error:  syntax error, unexpected '[' in /root/WhatsBot/class/StringParser.php on line 9

**Comment by fermino** [comment]
It is beacuse you're using PHP < 5.3. I'll fix it tonight...

**Comment by fermino** [comment]
Tell me if it's working fine...
