### ISSUE TITLE
Issue with the latest Commit

### ISSUE THREAD

**Issue by uppaljs** [fermino/WhatsBot#23]
Hi,

I am getting the following - WhatsBot logs in , but doesn't respond to anything , except after a little while i get the below error.

[root@t60 WhatsBot]# php WhatsBot.php
Checking updates...
WhatsBot is updated...

Cleaning temp directory...
Temp directory cleaned...

Connecting...
Connected...

Logging in...
Logged in...

Loading Threads...
Can't load Threads. You have to install PThreads extension.
See http://php.net/manual/en/pthreads.installation.php
Windows builds: http://windows.php.net/downloads/pecl/releases/pthreads/

Listening...

PHP Warning:  socket_write(): unable to write to socket [104]: Connection reset by peer in /root/WhatsBot/class/whatsapi/whatsprot.class.php on line 3618
PHP Warning:  socket_write(): unable to write to socket [32]: Broken pipe in /root/WhatsBot/class/whatsapi/whatsprot.class.php on line 3618

PHP Warning:  socket_write(): unable to write to socket [32]: Broken pipe in /root/WhatsBot/class/whatsapi/whatsprot.class.php on line 3618
PHP Warning:  socket_write(): unable to write to socket [32]: Broken pipe in /root/WhatsBot/class/whatsapi/whatsprot.class.php on line 3618
PHP Warning:  socket_write(): unable to write to socket [32]: Broken pipe in /root/WhatsBot/class/whatsapi/whatsprot.class.php on line 3618
... [Same warning] ...

PHP Fatal error:  Uncaught exception 'Exception' with message 'Tree length did not match received length (buff = 2264 & treeLength = 2865)' in /root/WhatsBot/class/whatsapi/whatsprot.class.php:3514
Stack trace:
#0 /root/WhatsBot/class/whatsapi/whatsprot.class.php(623): WhatsProt->readStanza()
#1 /root/WhatsBot/class/WhatsBot.php(116): WhatsProt->pollMessage()
#2 /root/WhatsBot/WhatsBot.php(7): WhatsBot->Listen()
#3 {main}
  thrown in /root/WhatsBot/class/whatsapi/whatsprot.class.php on line 3514
[root@t60 WhatsBot]#

**Comment by fermino** [comment]
I'll test and update WhatsAPI...

**Comment by fermino** [comment]
<https://github.com/mgp25/WhatsAPI-Official/issues/352#issuecomment-73472589> Maybe?

**Comment by uppaljs** [comment]
Nope , i don't think so , I only have 3 groups.

**Comment by fermino** [comment]
@uppaljs And the internet connection?

**Comment by uppaljs** [comment]
its okay as well - no issues at all.

**Comment by fermino** [comment]
:D

**Comment by uppaljs** [comment]
so - its not going to work :( ?

**Comment by fermino** [comment]
:c What PHP version are you using?

**Comment by fermino** [comment]
@uppaljs Does it work now? (v1.0a)

**Comment by uppaljs** [comment]
Just set it up now and it works great for the commands implemented!  Good Job man! The current modules are echo , exchange , help , md5 , search , translate right?

**Comment by fermino** [comment]
Thanks! :D
Yeap, I'm working in the old modules (like soundcloud, imgur uploader)...

**Comment by fermino** [comment]
All connection troubles fixeds (v2.0)
<https://github.com/fermino/WhatsBot/issues/49#issuecomment-107241324>
<https://github.com/fermino/WhatsBot/issues/44#issuecomment-107253109>
