### ISSUE TITLE
Fix some code issues

### ISSUE THREAD

**Issue by fermino** [fermino/WhatsBot#28]
Things like <https://codeclimate.com/github/fermino/WhatsBot/issues> and bot's structure. 
Working on <https://github.com/fermino/WhatsBot/tree/v1.0a>

ETA: 03-15-2015

**Comment by uppaljs** [comment]
@fermino  , is v1.0 in a running state ?

**Comment by fermino** [comment]
It is a new version, more efficient and with more features :D
But it's the same thing at all...

**Comment by fermino** [comment]
<https://github.com/fermino/WhatsBot/pull/31>
