### ISSUE TITLE
Is the new code working?

### ISSUE THREAD

**Issue by saadmeman** [fermino/WhatsBot#30]

**Comment by fermino** [comment]
v1.0 alpha?
Yeah, it works, but it's not ready yet. 

Some things that I have to do: 
* Add MultiMedia modules
* Add thread system
* Add Parser system (or some AI, v1.1/2)
* Fix some API/connection troubles

ETA for this release is in eight days :P

**Comment by saadmeman** [comment]
8 days :( , can u make it before 14 March plzz , if possible..

**Comment by fermino** [comment]
I will try ;)

**Comment by fermino** [comment]
Connection troubles fixed #27
I'm finishing the media modules system <https://github.com/fermino/WhatsBot/commit/82691c8bd0d8b8df40d95202af821eaec1c09d42>
:D

**Comment by fermino** [comment]
Media modules system is ready. 
I will leave the thread & parser system to 1.1/2. 

I have to test all it. If everything works properly, tomorrow i will be publishing the new version!

**Comment by saadmeman** [comment]
I am waiting eagerly..:) tq fermino.
