### ISSUE TITLE
Add old modules to v1.0

### ISSUE THREAD

**Issue by fermino** [fermino/WhatsBot#32]
<https://github.com/fermino/WhatsBot/tree/v1.0a>

**Comment by saadmeman** [comment]
is the working now?

**Comment by fermino** [comment]
Nope, some core features are different now. I will start right now with this ;)

**Comment by saadmeman** [comment]
ok..:)

**Comment by fermino** [comment]
@saadmeman Some modules are working ;)

**Comment by fermino** [comment]
Update, I'm working in v1.0a branch.

**Comment by saadmeman** [comment]
which modules are working , if possible add wiki and google first :)

**Comment by fermino** [comment]
You can call modules with something like

`!<module name> <params>`
Example, `!echo Hi!`

Command::Echo(String)
Command::Exchange(From, To [Amount], [Decimal places])
Command::Help([Module])
Command::MD5(Text)
Command::Translate(From, To, Text)

I will add Command::Search and Command::Wiki today, and I'll try to work in other modules (Media, Domain and extension).

**Comment by saadmeman** [comment]
ok :)

**Comment by fermino** [comment]
Command::Search added. 

There is a new module, Command::Admin
