### ISSUE TITLE
Feature Request :: Google Flight Search

### ISSUE THREAD

**Issue by uppaljs** [fermino/WhatsBot#35]
Hi @fermino 

It would be very cool to have support for searching google flights , I have dug up a web-page with the details to implement it , Unfortunately don't have enough time on my hand these days to implement it myself but it will be a very cool feature.

http://www.nohup.in/blog/using-json-google-flights

Cheers! 

btw - the new version is much better (Y)

**Comment by fermino** [comment]
I will research and try ;)
