### ISSUE TITLE
Exception in latest code

### ISSUE THREAD

**Issue by uppaljs** [fermino/WhatsBot#44]
php -v
PHP 5.6.4 (cli) (built: Dec 17 2014 16:47:40)
Copyright (c) 1997-2014 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2014 Zend Technologies

[INFO] [MODULES] Loading
[INFO] [MODULES] Ready!

[INFO] [THREADS] Loading
[WARNING] [THREADS] Can't load threads
If you want to use threads, you have to install PThreads extension
See http://php.net/manual/en/pthreads.installation.php
Windows builds: http://windows.php.net/downloads/pecl/releases/pthreads/
You can disable threads by setting config/Threads.json[enabled] to false

[INFO] [EVENTS] Binding listener
[INFO] [EVENTS] Ready!

[INFO] [WHATSBOT] Connecting
[INFO] [WHATSBOT] Connected!

[INFO] [WHATSBOT] Logging in
[INFO] [WHATSBOT] Ready!

[INFO] [WHATSBOT] Start time is 1427821436

[INFO] [WHATSBOT] Listening...
PHP Fatal error:  Uncaught exception 'ConnectionException' with message 'Tree length did not match received length (buff = 46 & treeLength = 95)' in /var/www/html/WhatsBot/class/whatsapi/whatsprot.class.php:3675
Stack trace:
#0 /var/www/html/WhatsBot/class/whatsapi/whatsprot.class.php(587): WhatsProt->readStanza()
#1 /var/www/html/WhatsBot/class/WhatsApp.php(48): WhatsProt->pollMessage(true)
#2 /var/www/html/WhatsBot/class/WhatsBot.php(133): WhatsApp->PollMessage()
#3 /var/www/html/WhatsBot/WhatsBot.php(13): WhatsBot->Listen()
#4 {main}
  thrown in /var/www/html/WhatsBot/class/whatsapi/whatsprot.class.php on line 3675

**Comment by fermino** [comment]
Try again, it must be one time problem :/

**Comment by uppaljs** [comment]
Tried it , works , but crashes after a little while.

**Comment by fermino** [comment]
Same exception?

**Comment by fermino** [comment]
@uppaljs see <https://github.com/fermino/WhatsBot/issues/49#issuecomment-107241324>.

**Comment by fermino** [comment]
Fixed :)
<https://github.com/fermino/WhatsBot/commit/0440d2a6036efd30cdbd0bfbeca2dff3c96f148f>

**Comment by fermino** [comment]
Fixed :) <https://github.com/fermino/WhatsBot/commit/0440d2a6036efd30cdbd0bfbeca2dff3c96f148f>

It will catch all exceptions and try to reconnect the bot.
