### ISSUE TITLE
can we have a module for changing status by command

### ISSUE THREAD

**Issue by saadmeman** [fermino/WhatsBot#51]

**Comment by fermino** [comment]
Yeap, add your number "<country code><number> in config/Admins.json

Then:
"!admin set status <My status message>" To set bot's status message
"!admin set picture <URL>" To set bot's profile picture

config/Admins.json example: 
```json
[
	[
		"your nick",
		"<country code><number>"
	]
]```

**Comment by saadmeman** [comment]
than you

**Comment by saadmeman** [comment]
i think i am having problem,

**Comment by fermino** [comment]
It must be 

```json
[
    [
        "saad",
        "91**********"
    ]
]
```

**Comment by saadmeman** [comment]
still no responce

**Comment by saadmeman** [comment]
it says
You need admin rights in order to do that
am i missing something

**Comment by fermino** [comment]
Uhm, if my number is +54 011 12345678, it will be "541112345678". Check if your number is complete in Admins.json :/

**Comment by saadmeman** [comment]
yeah it is

**Comment by fermino** [comment]
Does it works?

**Comment by saadmeman** [comment]
no

**Comment by fermino** [comment]
:/ Send me your number by email, with country code and all of it

**Comment by saadmeman** [comment]
give me your email id

**Comment by fermino** [comment]
fermino.github@gmail.com

**Comment by saadmeman** [comment]
sent

**Comment by fermino** [comment]
Sorry, i didn't saw your message. 
If it doesn't work, find onGetMessage function in `class/Listener.php`
```php
public function onGetMessage($Me, $From, $ID, $Type, $Time, $Name, $Text)
{
	$this->Parser->ParseTextMessage($Me, $From, $From, $ID, $Type, $Time, $Name, $Text);
	var_dump($From);
}
```

And add that `var_dump`. 

Then, start the bot and send some message. 
The console will show something like `xxxxxxxxx@whatsapp.net`. 
Copy the x's, it is what you have to add into `config/Admins.json`. 


If you are using v2.0, find the same function in the same file and add `var_dump($Message);`. It will display an array with all the message info.
