### ISSUE TITLE
Error when start 

### ISSUE THREAD

**Issue by coolerfire** [fermino/WhatsBot#71]
Hi, i've got this error when i try to start up the bot. Actually I've already configure the WhatsBot.json.

[Info] [Libs] Loading
[Warning] [Config] No such file config/Libs.json
[Warning] [Libs] Config file is not an array
[Warning] [Config] No such file config/WhatsBot.json

Fatal error: Uncaught exception 'Exception' with message 'You have to setup the config file config/WhatsBot.json' in C:\bla..bla..bla..\WhatsBot.php:75

**Comment by fermino** [comment]
Download the latest release (I'm making some changes in the file managing system) and try again and remember executing it from the main WhatsBot's directory. 

Regards ;)
-fermino-

**Comment by coolerfire** [comment]
Now i'm using WhatsBot 2.0.4.. i've got this error ->

[Warning] [Threads] Can't load threads. PThreads extension is not installed

[Info] [Events] Loading
[Info] [Events] ConnectionListener : Connection binded
[Info] [Events] WhatsBotListener : WhatsBot binded
[Info] [Events] StorageListener : Storage binded
[Info] [Events] Ready!
[Info] [WhatsBot] Connecting

It says Connecting but..the bot still offline.

p/s: i'm using php v 5.5 and already install PThreads .

Thank you

**Comment by fermino** [comment]
Uhm, try executing it with debug enabled php WhatsBot.php -d). If it shows
nothing more, we have a bigger problem here.

Whats OS are you using?
