### ISSUE TITLE
Help Needed : Getting User's Online Presence

### ISSUE THREAD

**Issue by rashid2538** [fermino/WhatsBot#76]
@fermino I'd like to thank you for this wonderful repository. I've configured WhatsBot and its working as expected. I'd like to know if there is any way I can get user's online presence. e. g., I'm logged as xxx@s.whatsapp.net and I want to check whether yyy@s.whatsapp.net is online or not.

I could not find any thing working for me on my own. Hope to hear from you soon.

Thanks in advance.

**Comment by fermino** [comment]
That kind of events (user online/offline, group creation and thinks like that) are planned to be added in 2.1 (#66). 

Now, you can do it by adding a custom listener (config/Listeners.json). 

You have to create a xListener.php inside class/Listeners, and a class with the same name, extending WhatsBotListenerCore, and there you can add any Chat-API event. 

I don't see that API from almost 2 months ago, and i don't know what event is, but: 

<https://github.com/WHAnonymous/Chat-API>

Regards!
-fermino-
