### ISSUE TITLE
Banned by WhatsApp? Telegram Messenger officially supports Bots

### ISSUE THREAD

**Issue by Erfahrungen** [fermino/WhatsBot#77]
Hi guys,

I've read that your WhatsApp was banned. Telegram supports Bots: www.telegram.me

Related: WhatsApp banned links to Telegram Messenger
http://www.androidpolice.com/2015/12/01/whatsapp-is-blocking-telegram-links-in-the-android-app/

Hope to see your Bot in Telegram.

Cheers
Marco

**Comment by fermino** [comment]
Well... In fact, whatsapp is only blocking some numbers from certain countries, 
About Telegram, I'm planning to make some extension to support it, but I have no time xD

Regards!
-fermino-
